<?xml version="1.0" encoding="UTF-8"?>
<robot generator="Robot 7.2.2 (Python 3.11.4 on darwin)" generated="2025-02-17T11:24:57.671038" rpa="false" schemaversion="5">
<suite id="s1" name="n8nTest" source="/Users/chaiyangeumpha/workshop_robot_framework/Robot-Framework_โจทย์ Class Project/n8nTest.robot">
<test id="s1-t1" name="สมัครสมาชิกของ Future Skill" line="75">
<kw name="เปิดเบราว์เซอร์เต็มจอ">
<kw name="Open Browser" owner="SeleniumLibrary">
<msg time="2025-02-17T11:24:57.751059" level="INFO">Opening browser 'chrome' to base url 'https://futureskill.co/'.</msg>
<arg>${baseUrl}</arg>
<arg>chrome</arg>
<doc>Opens a new browser instance to the optional ``url``.</doc>
<status status="PASS" start="2025-02-17T11:24:57.750943" elapsed="6.972624"/>
</kw>
<kw name="Maximize Browser Window" owner="SeleniumLibrary">
<msg time="2025-02-17T11:25:35.717032" level="WARN">Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x106b9f850&gt;: Failed to establish a new connection: [Errno 61] Connection refused')': /session/6e07d5886910e329e15c141b5610202f/screenshot</msg>
<msg time="2025-02-17T11:25:35.717810" level="WARN">Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x106b9fd50&gt;: Failed to establish a new connection: [Errno 61] Connection refused')': /session/6e07d5886910e329e15c141b5610202f/screenshot</msg>
<msg time="2025-02-17T11:25:35.718325" level="WARN">Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x106bbc810&gt;: Failed to establish a new connection: [Errno 61] Connection refused')': /session/6e07d5886910e329e15c141b5610202f/screenshot</msg>
<msg time="2025-02-17T11:25:35.718800" level="WARN">Keyword 'Capture Page Screenshot' could not be run on failure: HTTPConnectionPool(host='localhost', port=61278): Max retries exceeded with url: /session/6e07d5886910e329e15c141b5610202f/screenshot (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x106bbd2d0&gt;: Failed to establish a new connection: [Errno 61] Connection refused'))</msg>
<msg time="2025-02-17T11:25:35.719013" level="FAIL">ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))</msg>
<doc>Maximizes current browser window.</doc>
<status status="FAIL" start="2025-02-17T11:25:04.730936" elapsed="30.996032">ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))</status>
</kw>
<status status="FAIL" start="2025-02-17T11:24:57.750600" elapsed="37.976578">ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))</status>
</kw>
<kw name="คลิกปุ่มสมัครสมาชิก">
<status status="NOT RUN" start="2025-02-17T11:25:35.727403" elapsed="0.000032"/>
</kw>
<kw name="Sleep" owner="BuiltIn">
<arg>10s</arg>
<doc>Pauses the test executed for the given time.</doc>
<status status="NOT RUN" start="2025-02-17T11:25:35.727524" elapsed="0.000015"/>
</kw>
<kw name="กรอกข้อมูลสมัครสมาชิก">
<status status="NOT RUN" start="2025-02-17T11:25:35.727616" elapsed="0.000014"/>
</kw>
<kw name="เลือกยอมรับข้อกําหนดการใช้งานของ Futureskill">
<status status="NOT RUN" start="2025-02-17T11:25:35.727694" elapsed="0.000012"/>
</kw>
<kw name="คลิกปุ่มสมัครสมาชิกหลังกรอกข้อมูล">
<status status="NOT RUN" start="2025-02-17T11:25:35.727768" elapsed="0.000018"/>
</kw>
<kw name="ตรวจสอบข้อความ OTP ที่แสดงหลังสมัครสมาชิก">
<status status="NOT RUN" start="2025-02-17T11:25:35.727842" elapsed="0.000013"/>
</kw>
<status status="FAIL" start="2025-02-17T11:24:57.750152" elapsed="37.977820">ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))</status>
</test>
<status status="FAIL" start="2025-02-17T11:24:57.671611" elapsed="38.056717"/>
</suite>
<statistics>
<total>
<stat pass="0" fail="1" skip="0">All Tests</stat>
</total>
<tag>
</tag>
<suite>
<stat name="n8nTest" id="s1" pass="0" fail="1" skip="0">n8nTest</stat>
</suite>
</statistics>
<errors>
<msg time="2025-02-17T11:25:35.717032" level="WARN">Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x106b9f850&gt;: Failed to establish a new connection: [Errno 61] Connection refused')': /session/6e07d5886910e329e15c141b5610202f/screenshot</msg>
<msg time="2025-02-17T11:25:35.717810" level="WARN">Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x106b9fd50&gt;: Failed to establish a new connection: [Errno 61] Connection refused')': /session/6e07d5886910e329e15c141b5610202f/screenshot</msg>
<msg time="2025-02-17T11:25:35.718325" level="WARN">Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x106bbc810&gt;: Failed to establish a new connection: [Errno 61] Connection refused')': /session/6e07d5886910e329e15c141b5610202f/screenshot</msg>
<msg time="2025-02-17T11:25:35.718800" level="WARN">Keyword 'Capture Page Screenshot' could not be run on failure: HTTPConnectionPool(host='localhost', port=61278): Max retries exceeded with url: /session/6e07d5886910e329e15c141b5610202f/screenshot (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x106bbd2d0&gt;: Failed to establish a new connection: [Errno 61] Connection refused'))</msg>
</errors>
</robot>
